model:
  base_learning_rate: 4.5e-6
  target: ning.modules.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 64
    lossconfig:
      target: ning.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 200
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16,8]
      dropout: 0.0

data:
  target: utils.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: ning.data.custom.CustomTrain
      params:
        training_images_list_file: some/us_image_train.txt
        size: 64
    validation:
      target: ning.data.custom.CustomTest
      params:
        test_images_list_file: some/us_image_val.txt
        size: 64