model:
  base_learning_rate: 1.0e-06
  target: ning.modules.diffusion.ddpm.CrossDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: coord
    image_size: 64
    channels: 3
    cond_stage_trainable: False
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ning.modules.diffusion.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 256
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 256
    first_stage_config: None
    cond_stage_config: None
  



data:
  target: utils.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: ning.data.rfdata.RFDataUsImageTrain
      params:
        training_images_list_file: some/us_image_train.txt
        size: 64
    validation:
      target: ning.data.rfdata.RFDataUsImageValidation
      params:
        test_images_list_file: some/us_image_val.txt
        size: 64